---

  - name: rabbitmq | cluster | stopping rabbitmq app
    command: rabbitmqctl stop_app
    become: true

  # This is necessary to be sure that the app will join the cluster.
  - name: rabbitmq | cluster | resetting rabbitmq app
    command: rabbitmqctl reset
    become: true

    # Assume that the first box in the inventory is the cluster master        
  - name: rabbitmq | cluster | join cluster
    command: rabbitmqctl join_cluster rabbit@{{ hostvars[groups['all'][0]]['inventory_hostname'] }}
    become: true

  - name: rabbitmq | cluster | start rabbitmq app
    command: rabbitmqctl start_app
    become: true

  - name: rabbitmq | cluster | gather cluster status information
    command: rabbitmqctl cluster_status
    register: cluster_status
    become: true

  - name: rabbitmq | cluster | Assert that all hostnames are reported in cluster_status
    assert: 
      that: 
        - "'{{ hostvars[item]['inventory_hostname'] }}' in cluster_status.stdout"
    with_items: "{{ groups['all'] }}"
