---

  - name: rabbitmq | cluster | stopping rabbitmq app
    command: rabbitmqctl stop_app
    become: true

  # This is necessary to be sure that the app will join the cluster.
  - name: rabbitmq | cluster | resetting rabbitmq app
    command: rabbitmqctl reset
    become: true

    # Assume that the first box in the inventory is the cluster master        
  - name: rabbitmq | cluster | join cluster
    command: rabbitmqctl join_cluster rabbit@{{ hostvars[groups['all'][0]]['inventory_hostname'] }}
    become: true

  - name: rabbitmq | cluster | start rabbitmq app
    command: rabbitmqctl start_app
    become: true

  - name: rabbitmq | cluster | check if clustering has worked 0
    command: rabbitmqctl cluster_status
    register: cluster_status
    become: true

  - name: rabbitmq | cluster | check if clustering has worked 1          
    debug: 
      msg: "{{ cluster_status }}"
