---

  - name: rabbitmq | install | ensure python-software-properties is installed
    apt: pkg=python-software-properties state=installed
    become: true

  - name: rabbitmq | install | add RabbitMQ trusted key
    apt_key: 
      url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc 
      state: present
    become: true

  - name: rabbitmq | install | add rabbitmq official apt repository
    apt_repository: 
      repo: 'deb http://www.rabbitmq.com/debian/ testing main' 
      state: present
    become: true

  - name: rabbitmq | install | install package
    apt: 
      name: "{{ item }}" 
      update_cache: yes 
      state: installed 
    with_items:
      - rabbitmq-server
    become: true
            
  - name: rabbitmq | install | enable rabbitmq plugins
    rabbitmq_plugin: 
      names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation 
      state: enabled
    become: true

  - name: rabbitmq | install | starting rabbitmq app
    command: rabbitmqctl start_app
    become: true

  - name: rabbitmq | install | add users
    rabbitmq_user: 
      user: "{{item}}" 
      password: "changeme"
      tags: "administrator,{{item}}"
      vhost: / 
      configure_priv: .* 
      write_priv: .* 
      read_priv: .* 
      state: present
    with_items:
      - user1
      - user2
    become: true

  - name: rabbitmq | install | remove default guest user
    rabbitmq_user: 
      user: guest 
      state: absent
    become: true

  - name: rabbitmq | install | restart rabbitmq
    service: 
      name: rabbitmq-server 
      state: restarted
    become: true

  - name: rabbitmq | install | ensure vhost /test is present
    rabbitmq_vhost: 
      name: /test 
      state: present
    become: true
 
  - name: rabbitmq | install | Update policy to ensure that all queues are mirrored across the cluster
    rabbitmq_policy:
      name: HA
      pattern: .*
    args:
      tags:
        ha-mode: all
    become: true

  - name: rabbitmq | install | stopping rabbitmq app
    command: rabbitmqctl stop_app
    become: true

  - name: rabbitmq | install | add common erlang cookie
    template:
      src: erlang.cookie.j2
      dest: "{{ erlang_cookie_file }}"
      owner: rabbitmq
      group: rabbitmq
      mode: 0400
      backup: yes
    become: true

  - name: rabbitmq | install | restart rabbitmq
    service: name=rabbitmq-server state=restarted
    become: true

  - name: rabbitmq | install | start rabbitmq app
    command: rabbitmqctl start_app
    become: true
