---

- name: rabbitmq | nameko | install nameko
  pip:
    name: nameko
  become: yes

- name: rabbitmq | nameko | add basic config
  template:
    src: nameko.conf.j2
    dest: "{{ nameko_config_file }}"
    backup: yes

- name: rabbitmq | nameko | add basic test service
  template:
    src: nameko.helloservice.j2
    dest: "{{ nameko_helloservice_file }}"
    backup: yes

- name: rabbitmq | nameko | run test service
  shell: nohup nameko run helloworld --config {{ nameko_config_file }} &
  register: hello_world_status

- name: rabbitmq | nameko | Check test service
  shell: echo "n.rpc.greeting_service.hello(name='bob')" | nameko shell --config {{ nameko_config_file }} | tr -d [:punct:]
  register: greeting_status

- name: rabbitmq | nameko | Assert that test service running
  assert:
    that:
      - '"Hello" in greeting_status.stdout_lines[0]'

